name: Mirror to GitLab

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror push to GitLab
        run: |
          git push --force --prune https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/zenjan1/ipmsg-torrent.git +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
